//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kodimax_ASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Golosina
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Golosina()
        {
            this.TicketGolosina = new HashSet<TicketGolosina>();
        }
    
        public int Id_Golosina { get; set; }
        public string Nombre { get; set; }
        public string Tipo { get; set; }
        public double Precio { get; set; }
        public string Imagen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketGolosina> TicketGolosina { get; set; }
    }
}
