//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kodimax_ASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketGolosina
    {
        public int Id_TicketGolosina { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Cantidad { get; set; }
        public double SubTotal { get; set; }
        public double Tax { get; set; }
        public double Total { get; set; }
        public double Pago { get; set; }
        public double Cambio { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public int id_empleado { get; set; }
        public int id_golosina { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual Golosina Golosina { get; set; }
    }
}
